# Generated by Django 2.2 on 2021-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_sentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdata',
            name='commentDate',
            field=models.CharField(default='My Awesome Blog', max_length=255),
        ),
    ]
